"use client";

import {
  createContext,
  useContext,
  useState,
  useEffect,
  type ReactNode,
} from "react";

export type Language =
  | "en"
  | "es"
  | "zh"
  | "fr"
  | "de"
  | "pt"
  | "it"
  | "hi"
  | "ru"
  | "ko"
  | "ar";

export const languages: { code: Language; label: string; flag: string }[] = [
  { code: "en", label: "English", flag: "🇺🇸" },
  { code: "es", label: "Español", flag: "🇪🇸" },
  { code: "zh", label: "中文", flag: "🇨🇳" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "de", label: "Deutsch", flag: "🇩🇪" },
  { code: "pt", label: "Português", flag: "🇧🇷" },
  { code: "it", label: "Italiano", flag: "🇮🇹" },
  { code: "hi", label: "हिन्दी", flag: "🇮🇳" },
  { code: "ru", label: "Русский", flag: "🇷🇺" },
  { code: "ko", label: "한국어", flag: "🇰🇷" },
  { code: "ar", label: "العربية", flag: "🇸🇦" },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("language") as Language | null;
    if (saved && languages.some((l) => l.code === saved)) {
      setLanguage(saved);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem("language", language);
    // Set document direction for RTL languages
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const t = (key: string): string => {
    const keys = key.split(".");
    let value: unknown = translations[language];
    for (const k of keys) {
      if (value && typeof value === "object" && k in value) {
        value = (value as Record<string, unknown>)[k];
      } else {
        // Fallback to English
        value = translations.en;
        for (const fallbackKey of keys) {
          if (value && typeof value === "object" && fallbackKey in value) {
            value = (value as Record<string, unknown>)[fallbackKey];
          } else {
            return key;
          }
        }
        break;
      }
    }
    return typeof value === "string" ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

// Translations object
const translations: Record<Language, Record<string, unknown>> = {
  en: {
    nav: {
      resume: "Andres Diaz Resume",
      resumeShort: "AD Resume",
      about: "About",
      skills: "Skills",
      tools: "Tools",
      philosophy: "Philosophy",
      education: "Education",
      portfolio: "Portfolio",
      contact: "Contact",
    },
    hero: {
      subtitle: "Multimedia Professional",
      name: "Andres Diaz",
      roles: "Graphic Designer / Filmmaker / Music Producer / Full-Stack Developer / Social Media Manager & Creative Technologist",
      description: "From cinematic storytelling to polished web applications, I craft end-to-end digital experiences that captivate audiences and drive real results. I help businesses, artists, and brands increase sales, gain exposure, and stand out with professional, creative visuals that stay ahead of the trends. With over a decade spanning film, photography, graphic design, music, and code, I bring a unique cross-disciplinary vision to every project.",
      viewWork: "View Work",
      contact: "Contact",
      resume: "Resume",
      scroll: "Scroll",
    },
    about: {
      title: "About",
      p1: "With over a decade of experience in multimedia production, I've built a career at the intersection of creativity and technology. From directing photo and video shoots to developing full-stack applications, my work spans the entire creative pipeline.",
      p2: "I founded AShutter Media to deliver high-impact visual content for brands, artists, and businesses. My approach combines technical precision with artistic vision, ensuring every project not only meets but exceeds expectations.",
      p3: "Whether it's a cinematic commercial, a dynamic social media campaign, or a custom web application, I bring the same level of dedication and craftsmanship to every project. I believe in the power of visual storytelling to connect, inspire, and drive results.",
    },
    skills: {
      title: "Skills & Disciplines",
      videoEditing: "Video Editing",
      videoEditingDesc: "Professional editing for commercials, films, social media, and corporate content using industry-standard tools.",
      photography: "Photography",
      photographyDesc: "Studio and location photography including portraits, products, events, and architectural work.",
      graphicDesign: "Graphic Design",
      graphicDesignDesc: "Brand identity, marketing materials, social media graphics, and publication design.",
      musicProduction: "Music Production",
      musicProductionDesc: "Original compositions, sound design, mixing, and mastering for various media formats.",
      webDevelopment: "Web Development",
      webDevelopmentDesc: "Full-stack development with modern frameworks, responsive design, and optimal performance.",
      appDevelopment: "App Development",
      appDevelopmentDesc: "Cross-platform mobile applications with intuitive interfaces and seamless user experiences.",
      socialMedia: "Social Media",
      socialMediaDesc: "Content strategy, community management, and growth optimization across all major platforms.",
      motionGraphics: "Motion Graphics",
      motionGraphicsDesc: "Animated graphics, visual effects, and dynamic content for digital and broadcast media.",
    },
    tools: {
      title: "Software & Tools",
      creativeSoftware: "Creative Software",
      workflowAutomation: "Workflow & Automation",
      osPlatforms: "Operating Systems & Platforms",
      hardware: "Hardware & Equipment",
      musicInstruments: "Music Instruments",
    },
    philosophy: {
      title: "Work Ethic & Philosophy",
      precisionTitle: "Precision & Quality",
      precisionDesc: "Every frame, every pixel, every line of code matters. I approach each project with meticulous attention to detail, ensuring the highest quality output that stands the test of time.",
      collaborationTitle: "Collaboration",
      collaborationDesc: "Great work emerges from great partnerships. I believe in open communication, understanding client visions deeply, and working together to exceed expectations.",
      innovationTitle: "Innovation",
      innovationDesc: "Staying ahead means constantly evolving. I embrace new technologies, techniques, and creative approaches to deliver cutting-edge solutions.",
      integrityTitle: "Integrity",
      integrityDesc: "Honesty and transparency form the foundation of every professional relationship. I deliver what I promise and communicate openly throughout every project.",
      languages: "Languages",
      workPreferences: "Work Preferences",
      remote: "Remote",
      onSite: "On-Site",
      hybrid: "Hybrid",
      freelance: "Freelance",
      fullTime: "Full-Time",
      contract: "Contract",
      professionalSkills: "Professional Skills",
      punctual: "Punctual & Reliable",
      teamPlayer: "Team Player",
      quickLearner: "Quick Learner",
      workEthic: "Strong Work Ethic",
      problemSolver: "Problem Solver",
      detailOriented: "Detail Oriented",
      adaptable: "Adaptable",
      selfMotivated: "Self-Motivated",
      creativeThinker: "Creative Thinker",
      leadership: "Leadership",
      timeManagement: "Time Management",
      clientRelations: "Client Relations",
      moreAboutMe: "More About Me",
      bornDate: "Born 09/13/1998",
      bornVenezuela: "Born in Venezuela",
      usCitizen: "US Citizen",
      loveTravel: "Love to Travel",
      contentCreator: "Content Creator",
      musicProducer: "Music Producer",
      youtubeChannels: "Multiple YouTube Channels",
      italianFood: "Italian Food Enthusiast",
      languageLearner: "Language Learner",
      loveDriving: "Love Driving",
      networking: "Networking & Building Connections",
      lifelongLearner: "Lifelong Learner",
    },
    education: {
      title: "Education",
      highSchool: "High School Diploma",
      highSchoolInst: "Secondary Education",
      highSchoolLoc: "General Studies & Foundation",
      highSchoolYear: "Completed",
      highSchoolDesc: "Completed secondary education with focus on foundational academics, developing early interests in technology, arts, and media production.",
      internationalStudies: "International Studies in Creative Media",
      internationalInst: "International Undergraduate Education",
      internationalLoc: "Multimedia Arts, Audiovisual Communication & Visual Media",
      internationalYear: "2014 - 2017",
      internationalDesc: "Completed structured undergraduate-level studies abroad focused on multimedia, video production, photography, and digital media. Curriculum aligned with international standards in visual storytelling, cinematography, video editing, graphic design, photography, and audio fundamentals. Academic experience recognized as Bachelor's degree equivalent in creative media.",
      continuingEd: "Continuing & Professional Development",
      continuingInst: "Ongoing Advanced Training, Certifications & Bachelor's Degree Coursework",
      continuingLoc: "Online & Internationally Recognized Platforms",
      continuingYear: "2017 - Present",
      areasOfTraining: "Areas of Ongoing Training",
      creativeTools: "Advanced Creative Tools",
      creativeToolsDesc: "Mastery of Adobe Creative Suite, DaVinci Resolve, Final Cut Pro, and emerging AI-powered creative tools.",
      photographyTraining: "Photography & Cinematography",
      photographyTrainingDesc: "Advanced lighting techniques, color grading, camera systems, and visual storytelling methods.",
      audioProduction: "Audio Production",
      audioProductionDesc: "Professional music production, sound design, mixing, mastering, and audio post-production.",
      marketingBusiness: "Marketing & Business",
      marketingBusinessDesc: "Digital marketing strategies, brand development, client relations, and business operations.",
      webAppDev: "Web & App Development",
      webAppDevDesc: "Modern frameworks (React, Next.js), full-stack development, mobile development, and cloud technologies.",
      leadershipSoftSkills: "Leadership & Soft Skills",
      leadershipSoftSkillsDesc: "Team collaboration, project leadership, communication, and continuous learning practices.",
    },
    contact: {
      title: "Let's Work Together",
      description: "Seeking a long-term role where I can commit fully. I bring dedication, reliability, and multidisciplinary creative and technical skills—ready to grow with your team and deliver consistent results as a committed team member.",
      glowDedication: "dedication",
      glowReliability: "reliability",
      glowGrow: "ready to grow with your team",
      emailMe: "Email Me",
      callText: "Call / Text",
      visitPortfolio: "Visit My Portfolio",
      findOnline: "Find me online",
    },
    footer: {
      rights: "All rights reserved.",
      checkPortfolio: "Check my portfolio",
    },
    scrollToTop: "Scroll to top",
    language: "Language",
    backToSite: "Back to site",
    downloadPdf: "Download PDF",
  },
  es: {
    nav: {
      resume: "Currículum de Andres Diaz",
      resumeShort: "CV AD",
      about: "Acerca",
      skills: "Habilidades",
      tools: "Herramientas",
      philosophy: "Filosofía",
      education: "Educación",
      portfolio: "Portafolio",
      contact: "Contacto",
    },
    hero: {
      subtitle: "Profesional Multimedia",
      name: "Andres Diaz",
      roles: "Diseñador Gráfico / Cineasta / Productor Musical / Desarrollador Full-Stack / Community Manager & Tecnólogo Creativo",
      description: "Desde narrativas cinematográficas hasta aplicaciones web pulidas, creo experiencias digitales completas que cautivan audiencias y generan resultados reales. Ayudo a empresas, artistas y marcas a aumentar ventas, ganar exposición y destacar con visuales profesionales y creativos que están a la vanguardia de las tendencias. Con más de una década en cine, fotografía, diseño gráfico, música y código, aporto una visión interdisciplinaria única a cada proyecto.",
      viewWork: "Ver Trabajo",
      contact: "Contacto",
      resume: "Currículum",
      scroll: "Desplazar",
    },
    about: {
      title: "Acerca de Mí",
      p1: "Con más de una década de experiencia en producción multimedia, he construido una carrera en la intersección de la creatividad y la tecnología. Desde dirigir sesiones de foto y video hasta desarrollar aplicaciones full-stack, mi trabajo abarca todo el proceso creativo.",
      p2: "Fundé AShutter Media para entregar contenido visual de alto impacto para marcas, artistas y empresas. Mi enfoque combina precisión técnica con visión artística, asegurando que cada proyecto no solo cumpla sino supere las expectativas.",
      p3: "Ya sea un comercial cinematográfico, una campaña dinámica de redes sociales o una aplicación web personalizada, aporto el mismo nivel de dedicación y artesanía a cada proyecto. Creo en el poder de la narrativa visual para conectar, inspirar y generar resultados.",
    },
    skills: {
      title: "Habilidades y Disciplinas",
      videoEditing: "Edición de Video",
      videoEditingDesc: "Edición profesional para comerciales, películas, redes sociales y contenido corporativo usando herramientas estándar de la industria.",
      photography: "Fotografía",
      photographyDesc: "Fotografía de estudio y locación incluyendo retratos, productos, eventos y trabajo arquitectónico.",
      graphicDesign: "Diseño Gráfico",
      graphicDesignDesc: "Identidad de marca, materiales de marketing, gráficos para redes sociales y diseño de publicaciones.",
      musicProduction: "Producción Musical",
      musicProductionDesc: "Composiciones originales, diseño de sonido, mezcla y masterización para varios formatos de medios.",
      webDevelopment: "Desarrollo Web",
      webDevelopmentDesc: "Desarrollo full-stack con frameworks modernos, diseño responsivo y rendimiento óptimo.",
      appDevelopment: "Desarrollo de Apps",
      appDevelopmentDesc: "Aplicaciones móviles multiplataforma con interfaces intuitivas y experiencias de usuario fluidas.",
      socialMedia: "Redes Sociales",
      socialMediaDesc: "Estrategia de contenido, gestión de comunidad y optimización de crecimiento en todas las plataformas principales.",
      motionGraphics: "Motion Graphics",
      motionGraphicsDesc: "Gráficos animados, efectos visuales y contenido dinámico para medios digitales y broadcast.",
    },
    tools: {
      title: "Software y Herramientas",
      creativeSoftware: "Software Creativo",
      workflowAutomation: "Flujo de Trabajo y Automatización",
      osPlatforms: "Sistemas Operativos y Plataformas",
      hardware: "Hardware y Equipo",
      musicInstruments: "Instrumentos Musicales",
    },
    philosophy: {
      title: "Ética de Trabajo y Filosofía",
      precisionTitle: "Precisión y Calidad",
      precisionDesc: "Cada cuadro, cada píxel, cada línea de código importa. Abordo cada proyecto con atención meticulosa al detalle, asegurando la más alta calidad que perdura en el tiempo.",
      collaborationTitle: "Colaboración",
      collaborationDesc: "El gran trabajo surge de grandes alianzas. Creo en la comunicación abierta, entender profundamente las visiones del cliente y trabajar juntos para superar expectativas.",
      innovationTitle: "Innovación",
      innovationDesc: "Mantenerse adelante significa evolucionar constantemente. Abrazo nuevas tecnologías, técnicas y enfoques creativos para entregar soluciones de vanguardia.",
      integrityTitle: "Integridad",
      integrityDesc: "La honestidad y transparencia forman la base de cada relación profesional. Entrego lo que prometo y me comunico abiertamente durante todo el proyecto.",
      languages: "Idiomas",
      workPreferences: "Preferencias de Trabajo",
      remote: "Remoto",
      onSite: "Presencial",
      hybrid: "Híbrido",
      freelance: "Freelance",
      fullTime: "Tiempo Completo",
      contract: "Contrato",
      professionalSkills: "Habilidades Profesionales",
      punctual: "Puntual y Confiable",
      teamPlayer: "Trabajo en Equipo",
      quickLearner: "Aprendizaje Rápido",
      workEthic: "Fuerte Ética de Trabajo",
      problemSolver: "Resolutor de Problemas",
      detailOriented: "Orientado al Detalle",
      adaptable: "Adaptable",
      selfMotivated: "Automotivado",
      creativeThinker: "Pensador Creativo",
      leadership: "Liderazgo",
      timeManagement: "Gestión del Tiempo",
      clientRelations: "Relaciones con Clientes",
      moreAboutMe: "Más Sobre Mí",
      bornDate: "Nacido 13/09/1998",
      bornVenezuela: "Nacido en Venezuela",
      usCitizen: "Ciudadano de EE.UU.",
      loveTravel: "Amo Viajar",
      contentCreator: "Creador de Contenido",
      musicProducer: "Productor Musical",
      youtubeChannels: "Múltiples Canales de YouTube",
      italianFood: "Entusiasta de la Comida Italiana",
      languageLearner: "Aprendiz de Idiomas",
      loveDriving: "Amo Conducir",
      networking: "Networking y Conexiones",
      lifelongLearner: "Aprendiz de por Vida",
    },
    education: {
      title: "Educación",
      highSchool: "Diploma de Bachillerato",
      highSchoolInst: "Educación Secundaria",
      highSchoolLoc: "Estudios Generales y Fundamentos",
      highSchoolYear: "Completado",
      highSchoolDesc: "Completé la educación secundaria con enfoque en fundamentos académicos, desarrollando intereses tempranos en tecnología, artes y producción de medios.",
      internationalStudies: "Estudios Internacionales en Medios Creativos",
      internationalInst: "Educación Internacional de Pregrado",
      internationalLoc: "Artes Multimedia, Comunicación Audiovisual y Medios Visuales",
      internationalYear: "2014 - 2017",
      internationalDesc: "Completé estudios estructurados de nivel universitario en el extranjero enfocados en multimedia, producción de video, fotografía y medios digitales. Plan de estudios alineado con estándares internacionales en narrativa visual, cinematografía, edición de video, diseño gráfico, fotografía y fundamentos de audio. Experiencia académica reconocida como equivalente a licenciatura en medios creativos.",
      continuingEd: "Desarrollo Profesional Continuo",
      continuingInst: "Capacitación Avanzada, Certificaciones y Cursos de Licenciatura en Curso",
      continuingLoc: "Plataformas en Línea y Reconocidas Internacionalmente",
      continuingYear: "2017 - Presente",
      areasOfTraining: "Áreas de Capacitación Continua",
      creativeTools: "Herramientas Creativas Avanzadas",
      creativeToolsDesc: "Dominio de Adobe Creative Suite, DaVinci Resolve, Final Cut Pro y herramientas creativas emergentes impulsadas por IA.",
      photographyTraining: "Fotografía y Cinematografía",
      photographyTrainingDesc: "Técnicas avanzadas de iluminación, gradación de color, sistemas de cámara y métodos de narrativa visual.",
      audioProduction: "Producción de Audio",
      audioProductionDesc: "Producción musical profesional, diseño de sonido, mezcla, masterización y postproducción de audio.",
      marketingBusiness: "Marketing y Negocios",
      marketingBusinessDesc: "Estrategias de marketing digital, desarrollo de marca, relaciones con clientes y operaciones comerciales.",
      webAppDev: "Desarrollo Web y de Apps",
      webAppDevDesc: "Frameworks modernos (React, Next.js), desarrollo full-stack, desarrollo móvil y tecnologías en la nube.",
      leadershipSoftSkills: "Liderazgo y habilidades blandas",
      leadershipSoftSkillsDesc: "Colaboración en equipo, liderazgo de proyectos, comunicación y prácticas de aprendizaje continuo.",
    },
    contact: {
      title: "Trabajemos Juntos",
      description: "Busco un rol a largo plazo donde pueda comprometerme por completo. Aporto dedicación, confiabilidad y habilidades creativas y técnicas multidisciplinarias—listo para crecer con tu equipo y entregar resultados consistentes como miembro comprometido.",
      glowDedication: "dedicación",
      glowReliability: "confiabilidad",
      glowGrow: "listo para crecer con tu equipo",
      emailMe: "Envíame un Email",
      callText: "Llamar / Mensaje",
      visitPortfolio: "Visitar Mi Portafolio",
      findOnline: "Encuéntrame en línea",
    },
    footer: {
      rights: "Todos los derechos reservados.",
      checkPortfolio: "Ver mi portafolio",
    },
    scrollToTop: "Ir arriba",
    language: "Idioma",
    backToSite: "Volver al sitio",
    downloadPdf: "Descargar PDF",
  },
  zh: {
    nav: {
      resume: "Andres Diaz 简历",
      resumeShort: "AD简历",
      about: "关于",
      skills: "技能",
      tools: "工具",
      philosophy: "理念",
      education: "教育",
      portfolio: "作品集",
      contact: "联系",
    },
    hero: {
      subtitle: "多媒体专业人士",
      name: "Andres Diaz",
      roles: "平面设计师 / 电影制作人 / 音乐制作人 / 全栈开发者 / 社交媒体经理与创意技术专家",
      description: "从电影叙事到精致的网络应用，我打造端到端的数字体验，吸引观众并带来真实成果。我帮助企业、艺术家和品牌增加销售、获得曝光，并以专业、创意的视觉效果脱颖而出，始终走在趋势前沿。凭借十多年在电影、摄影、平面设计、音乐和编程领域的经验，我为每个项目带来独特的跨学科视野。",
      viewWork: "查看作品",
      contact: "联系",
      resume: "简历",
      scroll: "滚动",
    },
    about: {
      title: "关于我",
      p1: "凭借十多年的多媒体制作经验，我在创意与技术的交汇处建立了自己的职业生涯。从指导照片和视频拍摄到开发全栈应用程序，我的工作涵盖整个创意流程。",
      p2: "我创立了AShutter Media，为品牌、艺术家和企业提供高影响力的视觉内容。我的方法将技术精度与艺术视野相结合，确保每个项目不仅满足而且超越期望。",
      p3: "无论是电影级商业广告、动态社交媒体活动还是定制网络应用，我都以同样的奉献精神和工艺对待每个项目。我相信视觉叙事的力量可以连接、启发并带来成果。",
    },
    skills: {
      title: "技能与专业",
      videoEditing: "视频编辑",
      videoEditingDesc: "使用行业标准工具为广告、电影、社交媒体和企业内容进行专业编辑。",
      photography: "摄影",
      photographyDesc: "工作室和外景摄影，包括人像、产品、活动和建筑作品。",
      graphicDesign: "平面设计",
      graphicDesignDesc: "品牌标识、营销材料、社交媒体图形和出版物设计。",
      musicProduction: "音乐制作",
      musicProductionDesc: "为各种媒体格式创作原创作品、声音设计、混音和母带处理。",
      webDevelopment: "网页开发",
      webDevelopmentDesc: "使用现代框架进行全栈开发，响应式设计和最佳性能。",
      appDevelopment: "应用开发",
      appDevelopmentDesc: "具有直观界面和无缝用户体验的跨平台移动应用程序。",
      socialMedia: "社交媒体",
      socialMediaDesc: "所有主要平台的内容策略、社区管理和增长优化。",
      motionGraphics: "动态图形",
      motionGraphicsDesc: "为数字和广播媒体制作动画图形、视觉效果和动态内容。",
    },
    tools: {
      title: "软件与工具",
      creativeSoftware: "创意软件",
      workflowAutomation: "工作流程与自动化",
      osPlatforms: "操作系统与平台",
      hardware: "硬件与设备",
      musicInstruments: "音乐器材",
    },
    philosophy: {
      title: "职业道德与理念",
      precisionTitle: "精确与质量",
      precisionDesc: "每一帧、每一像素、每一行代码都很重要。我以细致入微的态度对待每个项目，确保最高质量的输出经得起时间的考验。",
      collaborationTitle: "协作",
      collaborationDesc: "伟大的作品源于伟大的合作。我相信开放的沟通，深入理解客户的愿景，共同努力超越期望。",
      innovationTitle: "创新",
      innovationDesc: "保持领先意味着不断进化。我拥抱新技术、新技术和创意方法，提供前沿解决方案。",
      integrityTitle: "诚信",
      integrityDesc: "诚实和透明是每段专业关系的基础。我兑现承诺，在整个项目中保持开放沟通。",
      languages: "语言能力",
      workPreferences: "工作偏好",
      remote: "远程",
      onSite: "现场",
      hybrid: "混合",
      freelance: "自由职业",
      fullTime: "全职",
      contract: "合同",
      professionalSkills: "专业技能",
      punctual: "准时可靠",
      teamPlayer: "团队合作",
      quickLearner: "快速学习",
      workEthic: "强烈的职业道德",
      problemSolver: "问题解决者",
      detailOriented: "注重细节",
      adaptable: "适应性强",
      selfMotivated: "自我激励",
      creativeThinker: "创意思维",
      leadership: "领导力",
      timeManagement: "时间管理",
      clientRelations: "客户关系",
      moreAboutMe: "更多关于我",
      bornDate: "出生于1998年9月13日",
      bornVenezuela: "出生于委内瑞拉",
      usCitizen: "美国公民",
      loveTravel: "热爱旅行",
      contentCreator: "内容创作者",
      musicProducer: "音乐制作人",
      youtubeChannels: "多个YouTube频道",
      italianFood: "意大利美食爱好者",
      languageLearner: "语言学习者",
      loveDriving: "热爱驾驶",
      networking: "社交与建立联系",
      lifelongLearner: "终身学习者",
    },
    education: {
      title: "教育背景",
      highSchool: "高中文凭",
      highSchoolInst: "中等教育",
      highSchoolLoc: "通识教育与基础",
      highSchoolYear: "已完成",
      highSchoolDesc: "完成中等教育，专注于基础学术，培养了对技术、艺术和媒体制作的早期兴趣。",
      internationalStudies: "创意媒体国际研究",
      internationalInst: "国际本科教育",
      internationalLoc: "多媒体艺术、视听传播与视觉媒体",
      internationalYear: "2014 - 2017",
      internationalDesc: "在国外完成了以多媒体、视频制作、摄影和数字媒体为重点的本科级结构化学习。课程符合视觉叙事、电影摄影、视频编辑、平面设计、摄影和音频基础的国际标准。学术经历被认可为创意媒体学士学位同等学历。",
      continuingEd: "持续专业发展",
      continuingInst: "持续高级培训、认证与学士学位课程",
      continuingLoc: "在线和国际认可平台",
      continuingYear: "2017 - 至今",
      areasOfTraining: "持续培训领域",
      creativeTools: "高级创意工具",
      creativeToolsDesc: "精通Adobe Creative Suite、DaVinci Resolve、Final Cut Pro和新兴的AI驱动创意工具。",
      photographyTraining: "摄影与电影摄影",
      photographyTrainingDesc: "高级照明技术、色彩分级、相机系统和视觉叙事方法。",
      audioProduction: "音频制作",
      audioProductionDesc: "专业音乐制作、声音设计、混音、母带处理和音频后期制作。",
      marketingBusiness: "营销与商业",
      marketingBusinessDesc: "数字营销策略、品牌发展、客户关系和业务运营。",
      webAppDev: "网页与应用开发",
      webAppDevDesc: "现代框架（React、Next.js）、全栈开发、移动开发和云技术。",
      leadershipSoftSkills: "领导力与软技能",
      leadershipSoftSkillsDesc: "团队协作、项目领导、沟通与持续学习实践。",
    },
    contact: {
      title: "让我们一起合作",
      description: "寻求能全心投入的长期职位。我具备敬业精神、可靠性与多领域创意及技术能力—愿与您的团队共同成长，作为全心投入的团队成员持续交付成果。",
      glowDedication: "敬业精神",
      glowReliability: "可靠性",
      glowGrow: "愿与您的团队共同成长",
      emailMe: "发邮件给我",
      callText: "电话 / 短信",
      visitPortfolio: "访问我的作品集",
      findOnline: "在线找到我",
    },
    footer: {
      rights: "版权所有。",
      checkPortfolio: "查看我的作品集",
    },
    scrollToTop: "回到顶部",
    language: "语言",
    backToSite: "返回网站",
    downloadPdf: "下载 PDF",
  },
  fr: {
    nav: {
      resume: "CV de Andres Diaz",
      resumeShort: "CV AD",
      about: "À propos",
      skills: "Compétences",
      tools: "Outils",
      philosophy: "Philosophie",
      education: "Éducation",
      portfolio: "Portfolio",
      contact: "Contact",
    },
    hero: {
      subtitle: "Professionnel Multimédia",
      name: "Andres Diaz",
      roles: "Designer Graphique / Cinéaste / Producteur Musical / Développeur Full-Stack / Gestionnaire de Médias Sociaux & Technologue Créatif",
      description: "De la narration cinématographique aux applications web raffinées, je crée des expériences numériques complètes qui captivent les audiences et génèrent des résultats réels. J'aide les entreprises, artistes et marques à augmenter leurs ventes, gagner en visibilité et se démarquer avec des visuels professionnels et créatifs en avance sur les tendances. Avec plus d'une décennie d'expérience en cinéma, photographie, design graphique, musique et code, j'apporte une vision interdisciplinaire unique à chaque projet.",
      viewWork: "Voir le Travail",
      contact: "Contact",
      resume: "CV",
      scroll: "Défiler",
    },
    about: {
      title: "À Propos",
      p1: "Avec plus d'une décennie d'expérience en production multimédia, j'ai construit une carrière à l'intersection de la créativité et de la technologie. De la direction de séances photo et vidéo au développement d'applications full-stack, mon travail couvre l'ensemble du processus créatif.",
      p2: "J'ai fondé AShutter Media pour fournir du contenu visuel à fort impact pour les marques, artistes et entreprises. Mon approche combine précision technique et vision artistique, garantissant que chaque projet non seulement répond mais dépasse les attentes.",
      p3: "Qu'il s'agisse d'une publicité cinématographique, d'une campagne dynamique sur les réseaux sociaux ou d'une application web personnalisée, j'apporte le même niveau de dévouement et de savoir-faire à chaque projet. Je crois au pouvoir de la narration visuelle pour connecter, inspirer et générer des résultats.",
    },
    skills: {
      title: "Compétences & Disciplines",
      videoEditing: "Montage Vidéo",
      videoEditingDesc: "Montage professionnel pour publicités, films, médias sociaux et contenu d'entreprise avec des outils standard de l'industrie.",
      photography: "Photographie",
      photographyDesc: "Photographie en studio et en extérieur incluant portraits, produits, événements et travaux architecturaux.",
      graphicDesign: "Design Graphique",
      graphicDesignDesc: "Identité de marque, matériel marketing, graphiques pour réseaux sociaux et design de publication.",
      musicProduction: "Production Musicale",
      musicProductionDesc: "Compositions originales, design sonore, mixage et mastering pour divers formats médiatiques.",
      webDevelopment: "Développement Web",
      webDevelopmentDesc: "Développement full-stack avec frameworks modernes, design responsive et performance optimale.",
      appDevelopment: "Développement d'Apps",
      appDevelopmentDesc: "Applications mobiles multiplateformes avec interfaces intuitives et expériences utilisateur fluides.",
      socialMedia: "Médias Sociaux",
      socialMediaDesc: "Stratégie de contenu, gestion de communauté et optimisation de la croissance sur toutes les plateformes majeures.",
      motionGraphics: "Motion Graphics",
      motionGraphicsDesc: "Graphiques animés, effets visuels et contenu dynamique pour médias numériques et diffusion.",
    },
    tools: {
      title: "Logiciels & Outils",
      creativeSoftware: "Logiciels Créatifs",
      workflowAutomation: "Flux de Travail & Automatisation",
      osPlatforms: "Systèmes d'Exploitation & Plateformes",
      hardware: "Matériel & Équipement",
      musicInstruments: "Instruments de Musique",
    },
    philosophy: {
      title: "Éthique de Travail & Philosophie",
      precisionTitle: "Précision & Qualité",
      precisionDesc: "Chaque image, chaque pixel, chaque ligne de code compte. J'aborde chaque projet avec une attention méticuleuse aux détails, garantissant la plus haute qualité qui résiste à l'épreuve du temps.",
      collaborationTitle: "Collaboration",
      collaborationDesc: "Un excellent travail naît d'excellents partenariats. Je crois en la communication ouverte, la compréhension profonde des visions des clients et le travail ensemble pour dépasser les attentes.",
      innovationTitle: "Innovation",
      innovationDesc: "Rester en avance signifie évoluer constamment. J'embrasse les nouvelles technologies, techniques et approches créatives pour fournir des solutions de pointe.",
      integrityTitle: "Intégrité",
      integrityDesc: "L'honnêteté et la transparence forment la base de chaque relation professionnelle. Je livre ce que je promets et communique ouvertement tout au long de chaque projet.",
      languages: "Langues",
      workPreferences: "Préférences de Travail",
      remote: "Télétravail",
      onSite: "Sur Site",
      hybrid: "Hybride",
      freelance: "Freelance",
      fullTime: "Temps Plein",
      contract: "Contrat",
      professionalSkills: "Compétences Professionnelles",
      punctual: "Ponctuel & Fiable",
      teamPlayer: "Travail d'Équipe",
      quickLearner: "Apprentissage Rapide",
      workEthic: "Forte Éthique de Travail",
      problemSolver: "Résolution de Problèmes",
      detailOriented: "Orienté Détail",
      adaptable: "Adaptable",
      selfMotivated: "Autonome",
      creativeThinker: "Penseur Créatif",
      leadership: "Leadership",
      timeManagement: "Gestion du Temps",
      clientRelations: "Relations Clients",
      moreAboutMe: "Plus Sur Moi",
      bornDate: "Né le 13/09/1998",
      bornVenezuela: "Né au Venezuela",
      usCitizen: "Citoyen Américain",
      loveTravel: "J'aime Voyager",
      contentCreator: "Créateur de Contenu",
      musicProducer: "Producteur Musical",
      youtubeChannels: "Plusieurs Chaînes YouTube",
      italianFood: "Passionné de Cuisine Italienne",
      languageLearner: "Apprenant de Langues",
      loveDriving: "J'aime Conduire",
      networking: "Réseautage & Connexions",
      lifelongLearner: "Apprenant à Vie",
    },
    education: {
      title: "Éducation",
      highSchool: "Diplôme de Lycée",
      highSchoolInst: "Éducation Secondaire",
      highSchoolLoc: "Études Générales & Fondations",
      highSchoolYear: "Complété",
      highSchoolDesc: "Éducation secondaire complétée avec focus sur les fondamentaux académiques, développant des intérêts précoces pour la technologie, les arts et la production médiatique.",
      internationalStudies: "Études Internationales en Médias Créatifs",
      internationalInst: "Éducation Internationale de Premier Cycle",
      internationalLoc: "Arts Multimédia, Communication Audiovisuelle & Médias Visuels",
      internationalYear: "2014 - 2017",
      internationalDesc: "Études structurées de niveau universitaire à l'étranger axées sur le multimédia, la production vidéo, la photographie et les médias numériques. Programme aligné sur les normes internationales en narration visuelle, cinématographie, montage vidéo, design graphique, photographie et fondamentaux audio. Expérience académique reconnue comme équivalent licence en médias créatifs.",
      continuingEd: "Développement Professionnel Continu",
      continuingInst: "Formation Avancée Continue, Certifications & Cours de Licence",
      continuingLoc: "Plateformes en Ligne & Internationalement Reconnues",
      continuingYear: "2017 - Présent",
      areasOfTraining: "Domaines de Formation Continue",
      creativeTools: "Outils Créatifs Avancés",
      creativeToolsDesc: "Maîtrise d'Adobe Creative Suite, DaVinci Resolve, Final Cut Pro et outils créatifs émergents alimentés par l'IA.",
      photographyTraining: "Photographie & Cinématographie",
      photographyTrainingDesc: "Techniques d'éclairage avancées, étalonnage des couleurs, systèmes de caméra et méthodes de narration visuelle.",
      audioProduction: "Production Audio",
      audioProductionDesc: "Production musicale professionnelle, design sonore, mixage, mastering et post-production audio.",
      marketingBusiness: "Marketing & Business",
      marketingBusinessDesc: "Stratégies de marketing digital, développement de marque, relations clients et opérations commerciales.",
      webAppDev: "Développement Web & Apps",
      webAppDevDesc: "Frameworks modernes (React, Next.js), développement full-stack, développement mobile et technologies cloud.",
      leadershipSoftSkills: "Leadership et compétences relationnelles",
      leadershipSoftSkillsDesc: "Collaboration en équipe, leadership de projet, communication et pratiques d'apprentissage continu.",
    },
    contact: {
      title: "Travaillons Ensemble",
      description: "À la recherche d'un rôle à long terme où m'engager pleinement. J'apporte dévouement, fiabilité et des compétences créatives et techniques multidisciplinaires—prêt à grandir avec votre équipe et à livrer des résultats constants en tant que membre d'équipe engagé.",
      glowDedication: "dévouement",
      glowReliability: "fiabilité",
      glowGrow: "prêt à grandir avec votre équipe",
      emailMe: "M'envoyer un Email",
      callText: "Appeler / SMS",
      visitPortfolio: "Visiter Mon Portfolio",
      findOnline: "Me trouver en ligne",
    },
    footer: {
      rights: "Tous droits réservés.",
      checkPortfolio: "Voir mon portfolio",
    },
    scrollToTop: "Retour en haut",
    language: "Langue",
    backToSite: "Retour au site",
    downloadPdf: "Télécharger PDF",
  },
  hi: {
    nav: {
      resume: "Andres Diaz का रिज्यूमे",
      resumeShort: "AD रिज्यूमे",
      about: "परिचय",
      skills: "कौशल",
      tools: "उपकरण",
      philosophy: "दर्शन",
      education: "शिक्षा",
      portfolio: "पोर्टफोलियो",
      contact: "संपर्क",
    },
    hero: {
      subtitle: "मल्टीमीडिया पेशेवर",
      name: "Andres Diaz",
      roles: "ग्राफिक डिजाइनर / फिल्म निर्माता / संगीत निर्माता / फुल-स्टैक डेवलपर / सोशल मीडिया मैनेजर और क्रिएटिव टेक्नोलॉजिस्ट",
      description: "सिनेमाई कहानी से लेकर पॉलिश वेब एप्लिकेशन तक, मैं एंड-टू-एंड डिजिटल अनुभव बनाता हूं जो दर्शकों को मोहित करते हैं और वास्तविक परिणाम देते हैं। मैं व्यवसायों, कलाकारों और ब्रांडों को बिक्री बढ़ाने, एक्सपोजर पाने और ट्रेंड से आगे रहने वाले पेशेवर, रचनात्मक विजुअल के साथ अलग दिखने में मदद करता हूं। फिल्म, फोटोग्राफी, ग्राफिक डिजाइन, संगीत और कोड में एक दशक से अधिक के अनुभव के साथ, मैं हर प्रोजेक्ट में एक अनोखा क्रॉस-डिसिप्लिनरी विजन लाता हूं।",
      viewWork: "काम देखें",
      contact: "संपर्क",
      resume: "रिज्यूमे",
      scroll: "स्क्रॉल",
    },
    about: {
      title: "मेरे बारे में",
      p1: "मल्टीमीडिया प्रोडक्शन में एक दशक से अधिक के अनुभव के साथ, मैंने रचनात्मकता और प्रौद्योगिकी के संगम पर अपना करियर बनाया है। फोटो और वीडियो शूट निर्देशित करने से लेकर फुल-स्टैक एप्लिकेशन विकसित करने तक, मेरा काम पूरी क्रिएटिव पाइपलाइन को कवर करता है।",
      p2: "मैंने ब्रांड्स, कलाकारों और व्यवसायों के लिए उच्च-प्रभाव वाली विजुअल कंटेंट देने के लिए AShutter Media की स्थापना की। मेरा दृष्टिकोण तकनीकी सटीकता को कलात्मक दृष्टि के साथ जोड़ता है, यह सुनिश्चित करता है कि हर प्रोजेक्ट न केवल उम्मीदों को पूरा करे बल्कि उनसे आगे निकले।",
      p3: "चाहे सिनेमाई कमर्शियल हो, डायनामिक सोशल मीडिया कैंपेन हो या कस्टम वेब एप्लिकेशन, मैं हर प्रोजेक्ट में समान स्तर की समर्पण और शिल्पकला लाता हूं। मैं विजुअल स्टोरीटेलिंग की शक्ति में विश्वास करता हूं जो जोड़ती है, प्रेरित करती है और परिणाम देती है।",
    },
    skills: {
      title: "कौशल और विषय",
      videoEditing: "वीडियो एडिटिंग",
      videoEditingDesc: "इंडस्ट्री-स्टैंडर्ड टूल्स का उपयोग करके कमर्शियल, फिल्मों, सोशल मीडिया और कॉर्पोरेट कंटेंट के लिए पेशेवर एडिटिंग।",
      photography: "फोटोग्राफी",
      photographyDesc: "पोर्ट्रेट, प्रोडक्ट्स, इवेंट्स और आर्किटेक्चरल वर्क सहित स्टूडियो और लोकेशन फोटोग्राफी।",
      graphicDesign: "ग्राफिक डिजाइन",
      graphicDesignDesc: "ब्रांड आइडेंटिटी, मार्केटिंग मटेरियल, सोशल मीडिया ग्राफिक्स और पब्लिकेशन डिजाइन।",
      musicProduction: "संगीत उत्पादन",
      musicProductionDesc: "विभिन्न मीडिया फॉर्मेट के लिए ओरिजिनल कंपोजिशन, साउंड डिजाइन, मिक्सिंग और मास्टरिंग।",
      webDevelopment: "वेब डेवलपमेंट",
      webDevelopmentDesc: "मॉडर्न फ्रेमवर्क, रिस्पॉन्सिव डिजाइन और ऑप्टिमल परफॉर्मेंस के साथ फुल-स्टैक डेवलपमेंट।",
      appDevelopment: "ऐप डेवलपमेंट",
      appDevelopmentDesc: "इंट्यूटिव इंटरफेस और सीमलेस यूजर एक्सपीरियंस के साथ क्रॉस-प्लेटफॉर्म मोबाइल एप्लिकेशन।",
      socialMedia: "सोशल मीडिया",
      socialMediaDesc: "सभी प्रमुख प्लेटफॉर्म पर कंटेंट स्ट्रैटेजी, कम्युनिटी मैनेजमेंट और ग्रोथ ऑप्टिमाइजेशन।",
      motionGraphics: "मोशन ग्राफिक्स",
      motionGraphicsDesc: "डिजिटल और ब्रॉडकास्ट मीडिया के लिए एनिमेटेड ग्राफिक्स, विजुअल इफेक्ट्स और डायनामिक कंटेंट।",
    },
    tools: {
      title: "सॉफ्टवेयर और उपकरण",
      creativeSoftware: "क्रिएटिव सॉफ्टवेयर",
      workflowAutomation: "वर्कफ्लो और ऑटोमेशन",
      osPlatforms: "ऑपरेटिंग सिस्टम और प्लेटफॉर्म",
      hardware: "हार्डवेयर और उपकरण",
      musicInstruments: "संगीत वाद्ययंत्र",
    },
    philosophy: {
      title: "कार्य नीति और दर्शन",
      precisionTitle: "सटीकता और गुणवत्ता",
      precisionDesc: "हर फ्रेम, हर पिक्सेल, कोड की हर लाइन मायने रखती है। मैं हर प्रोजेक्ट को सूक्ष्म ध्यान से देखता हूं, उच्चतम गुणवत्ता सुनिश्चित करता हूं जो समय की कसौटी पर खरी उतरे।",
      collaborationTitle: "सहयोग",
      collaborationDesc: "महान काम महान साझेदारी से उभरता है। मैं खुले संवाद, क्लाइंट विजन को गहराई से समझने और उम्मीदों से आगे निकलने के लिए मिलकर काम करने में विश्वास करता हूं।",
      innovationTitle: "नवाचार",
      innovationDesc: "आगे रहने का मतलब है लगातार विकसित होना। मैं नई तकनीकों, तकनीकों और रचनात्मक दृष्टिकोणों को अपनाता हूं।",
      integrityTitle: "ईमानदारी",
      integrityDesc: "ईमानदारी और पारदर्शिता हर पेशेवर रिश्ते की नींव है। मैं जो वादा करता हूं वह देता हूं और हर प्रोजेक्ट में खुलकर संवाद करता हूं।",
      languages: "भाषाएं",
      workPreferences: "कार्य प्राथमिकताएं",
      remote: "रिमोट",
      onSite: "ऑन-साइट",
      hybrid: "हाइब्रिड",
      freelance: "फ्रीलांस",
      fullTime: "फुल-टाइम",
      contract: "कॉन्ट्रैक्ट",
      professionalSkills: "पेशेवर कौशल",
      punctual: "समयनिष्ठ और विश्वसनीय",
      teamPlayer: "टीम प्लेयर",
      quickLearner: "तेज सीखने वाला",
      workEthic: "मजबूत कार्य नैतिकता",
      problemSolver: "समस्या समाधानकर्ता",
      detailOriented: "विस्तार उन्मुख",
      adaptable: "अनुकूलनीय",
      selfMotivated: "स्व-प्रेरित",
      creativeThinker: "रचनात्मक विचारक",
      leadership: "नेतृत्व",
      timeManagement: "समय प्रबंधन",
      clientRelations: "क्लाइंट संबंध",
      moreAboutMe: "मेरे बारे में और",
      bornDate: "जन्म 13/09/1998",
      bornVenezuela: "वेनेजुएला में जन्म",
      usCitizen: "अमेरिकी नागरिक",
      loveTravel: "यात्रा पसंद",
      contentCreator: "कंटेंट क्रिएटर",
      musicProducer: "संगीत निर्माता",
      youtubeChannels: "एकाधिक YouTube चैनल",
      italianFood: "इतालवी भोजन प्रेमी",
      languageLearner: "भाषा सीखने वाला",
      loveDriving: "ड्राइविंग पसंद",
      networking: "नेटवर्किंग और कनेक्शन",
      lifelongLearner: "आजीवन सीखने वाला",
    },
    education: {
      title: "शिक्षा",
      highSchool: "हाई स्कूल डिप्लोमा",
      highSchoolInst: "माध्यमिक शिक्षा",
      highSchoolLoc: "सामान्य अध्ययन और नींव",
      highSchoolYear: "पूर्ण",
      highSchoolDesc: "मूलभूत शिक्षाविदों पर ध्यान केंद्रित करते हुए माध्यमिक शिक्षा पूरी की, प्रौद्योगिकी, कला और मीडिया उत्पादन में शुरुआती रुचि विकसित की।",
      internationalStudies: "क्रिएटिव मीडिया में अंतर्राष्ट्रीय अध्ययन",
      internationalInst: "अंतर्राष्ट्रीय स्नातक शिक्षा",
      internationalLoc: "मल्टीमीडिया कला, ऑडियोविजुअल कम्युनिकेशन और विजुअल मीडिया",
      internationalYear: "2014 - 2017",
      internationalDesc: "मल्टीमीडिया, वीडियो प्रोडक्शन, फोटोग्राफी और डिजिटल मीडिया पर केंद्रित विदेश में संरचित स्नातक-स्तरीय अध्ययन पूरा किया।",
      continuingEd: "सतत और पेशेवर विकास",
      continuingInst: "चल रहे उन्नत प्रशिक्षण, प्रमाणपत्र और बैचलर डिग्री कोर्सवर्क",
      continuingLoc: "ऑनलाइन और अंतर्राष्ट्रीय स्तर पर मान्यता प्राप्त प्लेटफॉर्म",
      continuingYear: "2017 - वर्तमान",
      areasOfTraining: "चल रहे प्रशिक्षण के क्षेत्र",
      creativeTools: "उन्नत क्रिएटिव टूल्स",
      creativeToolsDesc: "Adobe Creative Suite, DaVinci Resolve, Final Cut Pro और उभरते AI-संचालित क्रिएटिव टूल्स में महारत।",
      photographyTraining: "फोटोग्राफी और सिनेमैटोग्राफी",
      photographyTrainingDesc: "उन्नत लाइटिंग तकनीक, कलर ग्रेडिंग, कैमरा सिस्टम और विजुअल स्टोरीटेलिंग विधियां।",
      audioProduction: "ऑडियो प्रोडक्शन",
      audioProductionDesc: "पेशेवर संगीत उत्पादन, साउंड डिजाइन, मिक्सिंग, मास्टरिंग और ऑडियो पोस्ट-प्रोडक्शन।",
      marketingBusiness: "मार्केटिंग और बिजनेस",
      marketingBusinessDesc: "डिजिटल मार्केटिंग रणनीतियां, ब्रांड विकास, क्लाइंट संबंध और व्यावसायिक संचालन।",
      webAppDev: "वेब और ऐप डेवलपमेंट",
      webAppDevDesc: "मॉडर्न फ्रेमवर्क (React, Next.js), फुल-स्टैक डेवलपमेंट, मोबाइल डेवलपमेंट और क्लाउड तकनीकें।",
      leadershipSoftSkills: "नेतृत्व और सॉफ्ट स्किल्स",
      leadershipSoftSkillsDesc: "टीम सहयोग, परियोजना नेतृत्व, संचार और निरंतर शिक्षण प्रथाएं।",
    },
    contact: {
      title: "आइए साथ मिलकर काम करें",
      description: "लंबी अवधि की भूमिका ढूंढ रहा हूं जहां मैं पूरी तरह समर्पित रह सकूं। मैं समर्पण, विश्वसनीयता और बहु-विषयक रचनात्मक व तकनीकी कौशल लाता हूं—आपकी टीम के साथ बढ़ने और समर्पित सदस्य के रूप में लगातार परिणाम देने के लिए तैयार।",
      glowDedication: "समर्पण",
      glowReliability: "विश्वसनीयता",
      glowGrow: "आपकी टीम के साथ बढ़ने",
      emailMe: "ईमेल करें",
      callText: "कॉल / टेक्स्ट",
      visitPortfolio: "मेरा पोर्टफोलियो देखें",
      findOnline: "मुझे ऑनलाइन खोजें",
    },
    footer: {
      rights: "सर्वाधिकार सुरक्षित।",
      checkPortfolio: "मेरा पोर्टफोलियो देखें",
    },
    scrollToTop: "ऊपर जाएं",
    language: "भाषा",
    backToSite: "साइट पर वापस",
    downloadPdf: "PDF डाउनलोड",
  },
  ru: {
    nav: {
      resume: "Резюме Andres Diaz",
      resumeShort: "Резюме AD",
      about: "Обо мне",
      skills: "Навыки",
      tools: "Инструменты",
      philosophy: "Философия",
      education: "Образование",
      portfolio: "Портфолио",
      contact: "Контакт",
    },
    hero: {
      subtitle: "Мультимедийный специалист",
      name: "Andres Diaz",
      roles: "Графический дизайнер / Режиссер / Музыкальный продюсер / Full-Stack разработчик / SMM-менеджер и Креативный технолог",
      description: "От кинематографического повествования до отточенных веб-приложений, я создаю комплексные цифровые впечатления, которые захватывают аудиторию и дают реальные результаты. Я помогаю бизнесу, артистам и брендам увеличивать продажи, получать охват и выделяться с помощью профессиональных, креативных визуальных решений, опережающих тренды. С более чем десятилетним опытом в кино, фотографии, графическом дизайне, музыке и программировании, я привношу уникальное междисциплинарное видение в каждый проект.",
      viewWork: "Смотреть работы",
      contact: "Контакт",
      resume: "Резюме",
      scroll: "Прокрутить",
    },
    about: {
      title: "Обо мне",
      p1: "С более чем десятилетним опытом в мультимедийном производстве, я построил карьеру на стыке креативности и технологий. От руководства фото и видеосъемками до разработки full-stack приложений, моя работа охватывает весь креативный процесс.",
      p2: "Я основал AShutter Media для создания высокоэффективного визуального контента для брендов, артистов и бизнеса. Мой подход сочетает техническую точность с художественным видением, гарантируя, что каждый проект не только соответствует, но и превосходит ожидания.",
      p3: "Будь то кинематографическая реклама, динамичная кампания в социальных сетях или пользовательское веб-приложение, я привношу одинаковый уровень самоотдачи и мастерства в каждый проект. Я верю в силу визуального сторителлинга для связи, вдохновения и достижения результатов.",
    },
    skills: {
      title: "Навыки и дисциплины",
      videoEditing: "Видеомонтаж",
      videoEditingDesc: "Профессиональный монтаж для рекламы, фильмов, социальных сетей и корпоративного контента с использованием отраслевых инструментов.",
      photography: "Фотография",
      photographyDesc: "Студийная и выездная фотография, включая портреты, продукты, мероприятия и архитектурные работы.",
      graphicDesign: "Графический дизайн",
      graphicDesignDesc: "Фирменный стиль, маркетинговые материалы, графика для социальных сетей и дизайн публикаций.",
      musicProduction: "Музыкальное производство",
      musicProductionDesc: "Оригинальные композиции, звуковой дизайн, сведение и мастеринг для различных медиаформатов.",
      webDevelopment: "Веб-разработка",
      webDevelopmentDesc: "Full-stack разработка с современными фреймворками, адаптивным дизайном и оптимальной производительностью.",
      appDevelopment: "Разработка приложений",
      appDevelopmentDesc: "Кроссплатформенные мобильные приложения с интуитивным интерфейсом и бесшовным пользовательским опытом.",
      socialMedia: "Социальные сети",
      socialMediaDesc: "Контент-стратегия, управление сообществом и оптимизация роста на всех основных платформах.",
      motionGraphics: "Моушн-графика",
      motionGraphicsDesc: "Анимированная графика, визуальные эффекты и динамический контент для цифровых и вещательных медиа.",
    },
    tools: {
      title: "Программы и инструменты",
      creativeSoftware: "Креативное ПО",
      workflowAutomation: "Рабочий процесс и автоматизация",
      osPlatforms: "Операционные системы и платформы",
      hardware: "Оборудование",
      musicInstruments: "Музыкальные инструменты",
    },
    philosophy: {
      title: "Рабочая этика и философия",
      precisionTitle: "Точность и качество",
      precisionDesc: "Каждый кадр, каждый пиксель, каждая строка кода важны. Я подхожу к каждому проекту с скрупулезным вниманием к деталям, обеспечивая высочайшее качество, которое выдерживает испытание временем.",
      collaborationTitle: "Сотрудничество",
      collaborationDesc: "Отличная работа рождается из отличных партнерств. Я верю в открытое общение, глубокое понимание видения клиента и совместную работу для превышения ожиданий.",
      innovationTitle: "Инновации",
      innovationDesc: "Оставаться впереди означает постоянно развиваться. Я принимаю новые технологии, техники и креативные подходы для предоставления передовых решений.",
      integrityTitle: "Честность",
      integrityDesc: "Честность и прозрачность составляют основу каждых профессиональных отношений. Я выполняю то, что обещаю, и общаюсь открыто на протяжении всего проекта.",
      languages: "Языки",
      workPreferences: "Предпочтения по работе",
      remote: "Удаленно",
      onSite: "В офисе",
      hybrid: "Гибрид",
      freelance: "Фриланс",
      fullTime: "Полная занятость",
      contract: "Контракт",
      professionalSkills: "Профессиональные навыки",
      punctual: "Пунктуальный и надежный",
      teamPlayer: "Командный игрок",
      quickLearner: "Быстро обучаемый",
      workEthic: "Сильная рабочая этика",
      problemSolver: "Решатель проблем",
      detailOriented: "Внимание к деталям",
      adaptable: "Адаптивный",
      selfMotivated: "Самомотивированный",
      creativeThinker: "Креативный мыслитель",
      leadership: "Лидерство",
      timeManagement: "Управление временем",
      clientRelations: "Работа с клиентами",
      moreAboutMe: "Больше обо мне",
      bornDate: "Родился 13.09.1998",
      bornVenezuela: "Родился в Венесуэле",
      usCitizen: "Гражданин США",
      loveTravel: "Люблю путешествовать",
      contentCreator: "Создатель контента",
      musicProducer: "Музыкальный продюсер",
      youtubeChannels: "Несколько YouTube-каналов",
      italianFood: "Любитель итальянской кухни",
      languageLearner: "Изучаю языки",
      loveDriving: "Люблю водить",
      networking: "Нетворкинг и связи",
      lifelongLearner: "Учусь всю жизнь",
    },
    education: {
      title: "Образование",
      highSchool: "Аттестат о среднем образовании",
      highSchoolInst: "Среднее образование",
      highSchoolLoc: "Общеобразовательные предметы и основы",
      highSchoolYear: "Завершено",
      highSchoolDesc: "Завершил среднее образование с фокусом на фундаментальных академических дисциплинах, развивая ранний интерес к технологиям, искусству и медиапроизводству.",
      internationalStudies: "Международные исследования в области креативных медиа",
      internationalInst: "Международное высшее образование",
      internationalLoc: "Мультимедийное искусство, аудиовизуальные коммуникации и визуальные медиа",
      internationalYear: "2014 - 2017",
      internationalDesc: "Завершил структурированное обучение бакалаврского уровня за рубежом с фокусом на мультимедиа, видеопроизводство, фотографию и цифровые медиа.",
      continuingEd: "Непрерывное профессиональное развитие",
      continuingInst: "Продвинутое обучение, сертификаты и курсы бакалавриата",
      continuingLoc: "Онлайн и международно признанные платформы",
      continuingYear: "2017 - настоящее время",
      areasOfTraining: "Области непрерывного обучения",
      creativeTools: "Продвинутые креативные инструменты",
      creativeToolsDesc: "Мастерство Adobe Creative Suite, DaVinci Resolve, Final Cut Pro и новых AI-инструментов.",
      photographyTraining: "Фотография и кинематография",
      photographyTrainingDesc: "Продвинутые техники освещения, цветокоррекция, камерные системы и методы визуального повествования.",
      audioProduction: "Аудиопроизводство",
      audioProductionDesc: "Профессиональное музыкальное производство, звуковой дизайн, сведение, мастеринг и аудиопостпродакшн.",
      marketingBusiness: "Маркетинг и бизнес",
      marketingBusinessDesc: "Стратегии цифрового маркетинга, развитие бренда, работа с клиентами и бизнес-операции.",
      webAppDev: "Веб и мобильная разработка",
      webAppDevDesc: "Современные фреймворки (React, Next.js), full-stack разработка, мобильная разработка и облачные технологии.",
      leadershipSoftSkills: "Лидерство и гибкие навыки",
      leadershipSoftSkillsDesc: "Командная работа, управление проектами, коммуникация и практика непрерывного обучения.",
    },
    contact: {
      title: "Давайте работать вместе",
      description: "Ищу долгосрочную позицию, где могу полностью посвятить себя работе. Приношу преданность, надёжность и многопрофильные творческие и технические навыки—готов расти вместе с вашей командой и стабильно добиваться результатов как преданный член команды.",
      glowDedication: "преданность",
      glowReliability: "надёжность",
      glowGrow: "готов расти вместе с вашей командой",
      emailMe: "Написать email",
      callText: "Позвонить / SMS",
      visitPortfolio: "Посетить портфолио",
      findOnline: "Найти меня онлайн",
    },
    footer: {
      rights: "Все права защищены.",
      checkPortfolio: "Посмотреть портфолио",
    },
    scrollToTop: "Наверх",
    language: "Язык",
    backToSite: "Назад на сайт",
    downloadPdf: "Скачать PDF",
  },
  ko: {
    nav: {
      resume: "Andres Diaz 이력서",
      resumeShort: "AD 이력서",
      about: "소개",
      skills: "기술",
      tools: "도구",
      philosophy: "철학",
      education: "교육",
      portfolio: "포트폴리오",
      contact: "연락처",
    },
    hero: {
      subtitle: "멀티미디어 전문가",
      name: "Andres Diaz",
      roles: "그래픽 디자이너 / 영화 제작자 / 음악 프로듀서 / 풀스택 개발자 / 소셜 미디어 매니저 & 크리에이티브 테크놀로지스트",
      description: "영화적 스토리텔링부터 세련된 웹 애플리케이션까지, 저는 청중을 사로잡고 실제 결과를 이끌어내는 엔드투엔드 디지털 경험을 만듭니다. 저는 기업, 아티스트, 브랜드가 판매를 늘리고, 노출을 얻고, 트렌드를 앞서가는 전문적이고 창의적인 비주얼로 돋보이도록 돕습니다. 영화, 사진, 그래픽 디자인, 음악, 코드 분야에서 10년 이상의 경험을 바탕으로, 모든 프로젝트에 독특한 학제간 비전을 제공합니다.",
      viewWork: "작업 보기",
      contact: "연락처",
      resume: "이력서",
      scroll: "스크롤",
    },
    about: {
      title: "소개",
      p1: "10년 이상의 멀티미디어 제작 경험을 바탕으로, 창의성과 기술의 교차점에서 커리어를 쌓아왔습니다. 사진 및 비디오 촬영 감독부터 풀스택 애플리케이션 개발까지, 제 작업은 전체 크리에이티브 파이프라인을 아우릅니다.",
      p2: "브랜드, 아티스트, 기업을 위한 고효과 비주얼 콘텐츠를 제공하기 위해 AShutter Media를 설립했습니다. 제 접근 방식은 기술적 정밀함과 예술적 비전을 결합하여 모든 프로젝트가 기대를 충족하고 초과하도록 보장합니다.",
      p3: "시네마틱 광고, 역동적인 소셜 미디어 캠페인, 맞춤형 웹 애플리케이션 등 모든 프로젝트에 동일한 수준의 헌신과 장인정신을 적용합니다. 저는 연결하고, 영감을 주고, 결과를 이끌어내는 비주얼 스토리텔링의 힘을 믿습니다.",
    },
    skills: {
      title: "기술 & 분야",
      videoEditing: "비디오 편집",
      videoEditingDesc: "업계 표준 도구를 사용한 광고, 영화, 소셜 미디어 및 기업 콘텐츠의 전문 편집.",
      photography: "사진",
      photographyDesc: "인물, 제품, 이벤트, 건축 작업을 포함한 스튜디오 및 로케이션 촬영.",
      graphicDesign: "그래픽 디자인",
      graphicDesignDesc: "브랜드 아이덴티티, 마케팅 자료, 소셜 미디어 그래픽 및 출판물 디자인.",
      musicProduction: "음악 제작",
      musicProductionDesc: "다양한 미디어 형식을 위한 오리지널 작곡, 사운드 디자인, 믹싱 및 마스터링.",
      webDevelopment: "웹 개발",
      webDevelopmentDesc: "최신 프레임워크, 반응형 디자인 및 최적의 성능을 갖춘 풀스택 개발.",
      appDevelopment: "앱 개발",
      appDevelopmentDesc: "직관적인 인터페이스와 원활한 사용자 경험을 갖춘 크로스 플랫폼 모바일 애플리케이션.",
      socialMedia: "소셜 미디어",
      socialMediaDesc: "모든 주요 플랫폼에서의 콘텐츠 전략, 커뮤니티 관리 및 성장 최적화.",
      motionGraphics: "모션 그래픽",
      motionGraphicsDesc: "디지털 및 방송 미디어를 위한 애니메이션 그래픽, 시각 효과 및 동적 콘텐츠.",
    },
    tools: {
      title: "소프트웨어 & 도구",
      creativeSoftware: "크리에이티브 소프트웨어",
      workflowAutomation: "워크플로우 & 자동화",
      osPlatforms: "운영 체제 & 플랫폼",
      hardware: "하드웨어 & 장비",
      musicInstruments: "악기",
    },
    philosophy: {
      title: "업무 윤리 & 철학",
      precisionTitle: "정밀함 & 품질",
      precisionDesc: "모든 프레임, 모든 픽셀, 모든 코드 라인이 중요합니다. 저는 세심한 주의를 기울여 각 프로젝트에 접근하며, 시간의 시험을 견디는 최고 품질의 결과물을 보장합니다.",
      collaborationTitle: "협업",
      collaborationDesc: "훌륭한 작업은 훌륭한 파트너십에서 나옵니다. 저는 열린 소통, 고객 비전의 깊은 이해, 기대를 초과하기 위한 협력을 믿습니다.",
      innovationTitle: "혁신",
      innovationDesc: "앞서 나간다는 것은 끊임없이 진화하는 것을 의미합니다. 저는 최첨단 솔루션을 제공하기 위해 새로운 기술, 기법 및 창의적 접근 방식을 수용합니다.",
      integrityTitle: "성실함",
      integrityDesc: "정직과 투명성은 모든 전문적 관계의 기초입니다. 저는 약속한 것을 전달하고 모든 프로젝트 전반에 걸쳐 공개적으로 소통합니다.",
      languages: "언어",
      workPreferences: "업무 선호도",
      remote: "원격",
      onSite: "현장",
      hybrid: "하이브리드",
      freelance: "프리랜서",
      fullTime: "정규직",
      contract: "계약직",
      professionalSkills: "전문 기술",
      punctual: "시간 엄수 & 신뢰성",
      teamPlayer: "팀 플레이어",
      quickLearner: "빠른 학습자",
      workEthic: "강한 업무 윤리",
      problemSolver: "문제 해결사",
      detailOriented: "세부 지향적",
      adaptable: "적응력",
      selfMotivated: "자기 동기부여",
      creativeThinker: "창의적 사고",
      leadership: "리더십",
      timeManagement: "시간 관리",
      clientRelations: "고객 관계",
      moreAboutMe: "더 많은 정보",
      bornDate: "1998년 9월 13일생",
      bornVenezuela: "베네수엘라 출생",
      usCitizen: "미국 시민권자",
      loveTravel: "여행 좋아함",
      contentCreator: "콘텐츠 크리에이터",
      musicProducer: "음악 프로듀서",
      youtubeChannels: "다수의 YouTube 채널",
      italianFood: "이탈리안 음식 애호가",
      languageLearner: "언어 학습자",
      loveDriving: "운전 좋아함",
      networking: "네트워킹 & 인맥",
      lifelongLearner: "평생 학습자",
    },
    education: {
      title: "교육",
      highSchool: "고등학교 졸업장",
      highSchoolInst: "중등 교육",
      highSchoolLoc: "일반 교육 & 기초",
      highSchoolYear: "완료",
      highSchoolDesc: "기초 학문에 초점을 맞춘 중등 교육을 완료하고 기술, 예술 및 미디어 제작에 대한 초기 관심을 발전시켰습니다.",
      internationalStudies: "크리에이티브 미디어 국제 연구",
      internationalInst: "국제 학부 교육",
      internationalLoc: "멀티미디어 예술, 시청각 커뮤니케이션 & 시각 미디어",
      internationalYear: "2014 - 2017",
      internationalDesc: "멀티미디어, 비디오 제작, 사진 및 디지털 미디어에 초점을 맞춘 해외에서의 구조화된 학부 수준 연구를 완료했습니다.",
      continuingEd: "지속적인 전문성 개발",
      continuingInst: "지속적인 고급 교육, 자격증 & 학사 학위 과정",
      continuingLoc: "온라인 & 국제적으로 인정받는 플랫폼",
      continuingYear: "2017 - 현재",
      areasOfTraining: "지속적인 교육 분야",
      creativeTools: "고급 크리에이티브 도구",
      creativeToolsDesc: "Adobe Creative Suite, DaVinci Resolve, Final Cut Pro 및 새로운 AI 기반 크리에이티브 도구 마스터.",
      photographyTraining: "사진 & 시네마토그래피",
      photographyTrainingDesc: "고급 조명 기술, 색보정, 카메라 시스템 및 시각적 스토리텔링 방법.",
      audioProduction: "오디오 제작",
      audioProductionDesc: "전문 음악 제작, 사운드 디자인, 믹싱, 마스터링 및 오디오 후반 작업.",
      marketingBusiness: "마케팅 & 비즈니스",
      marketingBusinessDesc: "디지털 마케팅 전략, 브랜드 개발, 고객 관계 및 비즈니스 운영.",
      webAppDev: "웹 & 앱 개발",
      webAppDevDesc: "최신 프레임워크(React, Next.js), 풀스택 개발, 모바일 개발 및 클라우드 기술.",
      leadershipSoftSkills: "리더십 및 소프트 스킬",
      leadershipSoftSkillsDesc: "팀 협업, 프로젝트 리더십, 커뮤니케이션 및 지속 학습 실천.",
    },
    contact: {
      title: "함께 일해요",
      description: "완전히 헌신할 수 있는 장기 역할을 찾고 있습니다. 헌신, 신뢰성, 다학제적 크리에이티브 및 기술 역량을 갖추었으며—팀과 함께 성장하고 헌신적인 팀원으로 꾸준한 성과를 내고자 합니다.",
      glowDedication: "헌신",
      glowReliability: "신뢰성",
      glowGrow: "팀과 함께 성장하고",
      emailMe: "이메일 보내기",
      callText: "전화 / 문자",
      visitPortfolio: "포트폴리오 방문",
      findOnline: "온라인에서 찾기",
    },
    footer: {
      rights: "모든 권리 보유.",
      checkPortfolio: "포트폴리오 보기",
    },
    scrollToTop: "맨 위로",
    language: "언어",
    backToSite: "사이트로 돌아가기",
    downloadPdf: "PDF 다운로드",
  },
  ar: {
    nav: {
      resume: "سيرة Andres Diaz",
      resumeShort: "سيرة AD",
      about: "حول",
      skills: "المهارات",
      tools: "الأدوات",
      philosophy: "الفلسفة",
      education: "التعليم",
      portfolio: "معرض الأعمال",
      contact: "اتصل",
    },
    hero: {
      subtitle: "محترف الوسائط المتعددة",
      name: "Andres Diaz",
      roles: "مصمم جرافيك / صانع أفلام / منتج موسيقي / مطور Full-Stack / مدير وسائل التواصل الاجتماعي ومبتكر تقني",
      description: "من السرد السينمائي إلى تطبيقات الويب المصقولة، أصنع تجارب رقمية شاملة تأسر الجماهير وتحقق نتائج حقيقية. أساعد الشركات والفنانين والعلامات التجارية على زيادة المبيعات والحصول على التعرض والتميز بمرئيات احترافية وإبداعية تسبق الاتجاهات. مع أكثر من عقد من الخبرة في السينما والتصوير والتصميم الجرافيكي والموسيقى والبرمجة، أقدم رؤية متعددة التخصصات فريدة لكل مشروع.",
      viewWork: "عرض الأعمال",
      contact: "اتصل",
      resume: "السيرة الذاتية",
      scroll: "مرر",
    },
    about: {
      title: "حولي",
      p1: "مع أكثر من عقد من الخبرة في إنتاج الوسائط المتعددة، بنيت مسيرة مهنية عند تقاطع الإبداع والتكنولوجيا. من إدارة جلسات التصوير الفوتوغرافي والفيديو إلى تطوير تطبيقات full-stack، يغطي عملي خط الإنتاج الإبداعي بالكامل.",
      p2: "أسست AShutter Media لتقديم محتوى مرئي عالي التأثير للعلامات التجارية والفنانين والشركات. يجمع نهجي بين الدقة التقنية والرؤية الفنية، مما يضمن أن كل مشروع لا يلبي التوقعات فحسب بل يتجاوزها.",
      p3: "سواء كان إعلانًا سينمائيًا أو حملة وسائط اجتماعية ديناميكية أو تطبيق ويب مخصص، أقدم نفس مستوى التفاني والحرفية لكل مشروع. أؤمن بقوة السرد المرئي للتواصل والإلهام وتحقيق النتائج.",
    },
    skills: {
      title: "المهارات والتخصصات",
      videoEditing: "تحرير الفيديو",
      videoEditingDesc: "تحرير احترافي للإعلانات والأفلام ووسائل التواصل الاجتماعي والمحتوى المؤسسي باستخدام أدوات معيارية.",
      photography: "التصوير الفوتوغرافي",
      photographyDesc: "تصوير استوديو وموقع يشمل الصور الشخصية والمنتجات والفعاليات والأعمال المعمارية.",
      graphicDesign: "التصميم الجرافيكي",
      graphicDesignDesc: "هوية العلامة التجارية ومواد التسويق ورسومات وسائل التواصل الاجتماعي وتصميم المطبوعات.",
      musicProduction: "إنتاج الموسيقى",
      musicProductionDesc: "تأليفات أصلية وتصميم صوتي ومزج وماسترينغ لتنسيقات وسائط متعددة.",
      webDevelopment: "تطوير الويب",
      webDevelopmentDesc: "تطوير full-stack مع أطر عمل حديثة وتصميم متجاوب وأداء مثالي.",
      appDevelopment: "تطوير التطبيقات",
      appDevelopmentDesc: "تطبيقات جوال متعددة المنصات مع واجهات بديهية وتجارب مستخدم سلسة.",
      socialMedia: "وسائل التواصل الاجتماعي",
      socialMediaDesc: "استراتيجية المحتوى وإدارة المجتمع وتحسين النمو عبر جميع المنصات الرئيسية.",
      motionGraphics: "الرسوم المتحركة",
      motionGraphicsDesc: "رسومات متحركة ومؤثرات بصرية ومحتوى ديناميكي للوسائط الرقمية والبث.",
    },
    tools: {
      title: "البرامج والأدوات",
      creativeSoftware: "البرامج الإبداعية",
      workflowAutomation: "سير العمل والأتمتة",
      osPlatforms: "أنظمة التشغيل والمنصات",
      hardware: "الأجهزة والمعدات",
      musicInstruments: "الآلات الموسيقية",
    },
    philosophy: {
      title: "أخلاقيات العمل والفلسفة",
      precisionTitle: "الدقة والجودة",
      precisionDesc: "كل إطار، كل بكسل، كل سطر من الكود مهم. أتعامل مع كل مشروع باهتمام دقيق بالتفاصيل، مما يضمن أعلى جودة تصمد أمام اختبار الزمن.",
      collaborationTitle: "التعاون",
      collaborationDesc: "العمل الرائع ينبثق من شراكات رائعة. أؤمن بالتواصل المفتوح وفهم رؤى العملاء بعمق والعمل معًا لتجاوز التوقعات.",
      innovationTitle: "الابتكار",
      innovationDesc: "البقاء في المقدمة يعني التطور المستمر. أتبنى التقنيات والأساليب والمناهج الإبداعية الجديدة لتقديم حلول متطورة.",
      integrityTitle: "النزاهة",
      integrityDesc: "الصدق والشفافية يشكلان أساس كل علاقة مهنية. أقدم ما أعد به وأتواصل بصراحة طوال كل مشروع.",
      languages: "اللغات",
      workPreferences: "تفضيلات العمل",
      remote: "عن بُعد",
      onSite: "في الموقع",
      hybrid: "هجين",
      freelance: "عمل حر",
      fullTime: "دوام كامل",
      contract: "عقد",
      professionalSkills: "المهارات المهنية",
      punctual: "دقيق وموثوق",
      teamPlayer: "عامل فريق",
      quickLearner: "سريع التعلم",
      workEthic: "أخلاقيات عمل قوية",
      problemSolver: "حلال المشاكل",
      detailOriented: "موجه للتفاصيل",
      adaptable: "قابل للتكيف",
      selfMotivated: "محفز ذاتيًا",
      creativeThinker: "مفكر إبداعي",
      leadership: "قيادة",
      timeManagement: "إدارة الوقت",
      clientRelations: "علاقات العملاء",
      moreAboutMe: "المزيد عني",
      bornDate: "مواليد 13/09/1998",
      bornVenezuela: "ولد في فنزويلا",
      usCitizen: "مواطن أمريكي",
      loveTravel: "أحب السفر",
      contentCreator: "صانع محتوى",
      musicProducer: "منتج موسيقي",
      youtubeChannels: "قنوات يوتيوب متعددة",
      italianFood: "عاشق الطعام الإيطالي",
      languageLearner: "متعلم لغات",
      loveDriving: "أحب القيادة",
      networking: "التواصل وبناء العلاقات",
      lifelongLearner: "متعلم مدى الحياة",
    },
    education: {
      title: "التعليم",
      highSchool: "شهادة الثانوية العامة",
      highSchoolInst: "التعليم الثانوي",
      highSchoolLoc: "دراسات عامة وأساسية",
      highSchoolYear: "مكتمل",
      highSchoolDesc: "أكملت التعليم الثانوي مع التركيز على الأسس الأكاديمية، وتطوير الاهتمامات المبكرة في التكنولوجيا والفنون وإنتاج الوسائط.",
      internationalStudies: "دراسات دولية في الوسائط الإبداعية",
      internationalInst: "تعليم جامعي دولي",
      internationalLoc: "فنون الوسائط المتعددة والاتصال السمعي البصري والوسائط المرئية",
      internationalYear: "2014 - 2017",
      internationalDesc: "أكملت دراسات منظمة على مستوى البكالوريوس في الخارج تركز على الوسائط المتعددة وإنتاج الفيديو والتصوير والوسائط الرقمية.",
      continuingEd: "التطوير المهني المستمر",
      continuingInst: "تدريب متقدم مستمر وشهادات ودورات بكالوريوس",
      continuingLoc: "منصات معترف بها دوليًا وعبر الإنترنت",
      continuingYear: "2017 - الحاضر",
      areasOfTraining: "مجالات التدريب المستمر",
      creativeTools: "أدوات إبداعية متقدمة",
      creativeToolsDesc: "إتقان Adobe Creative Suite و DaVinci Resolve و Final Cut Pro وأدوات إبداعية ناشئة مدعومة بالذكاء الاصطناعي.",
      photographyTraining: "التصوير والسينماتوغرافيا",
      photographyTrainingDesc: "تقنيات الإضاءة المتقدمة وتدريج الألوان وأنظمة الكاميرا وطرق السرد المرئي.",
      audioProduction: "إنتاج الصوت",
      audioProductionDesc: "إنتاج موسيقي احترافي وتصميم صوتي ومزج وماسترينغ ومرحلة ما بعد الإنتاج الصوتي.",
      marketingBusiness: "التسويق والأعمال",
      marketingBusinessDesc: "استراتيجيات التسويق الرقمي وتطوير العلامة التجارية وعلاقات العملاء والعمليات التجارية.",
      webAppDev: "تطوير الويب والتطبيقات",
      webAppDevDesc: "أطر عمل حديثة (React, Next.js)، تطوير full-stack، تطوير الجوال وتقنيات السحابة.",
      leadershipSoftSkills: "القيادة والمهارات الناعمة",
      leadershipSoftSkillsDesc: "التعاون الجماعي، قيادة المشاريع، التواصل وممارسات التعلم المستمر.",
    },
    contact: {
      title: "لنعمل معًا",
      description: "أبحث عن دور طويل الأمد أستطيع فيه الالتزام بالكامل. أقدم التفاني والموثوقية ومهارات إبداعية وتقنية متعددة التخصصات—مستعد للنمو مع فريقك وتقديم نتائج متسقة كعضو ملتزم.",
      glowDedication: "التفاني",
      glowReliability: "الموثوقية",
      glowGrow: "مستعد للنمو مع فريقك",
      emailMe: "راسلني",
      callText: "اتصل / رسالة",
      visitPortfolio: "زيارة معرض أعمالي",
      findOnline: "جدني على الإنترنت",
    },
    footer: {
      rights: "جميع الحقوق محفوظة.",
      checkPortfolio: "عرض معرض أعمالي",
    },
    scrollToTop: "العودة للأعلى",
    language: "اللغة",
    backToSite: "العودة للموقع",
    downloadPdf: "تحميل PDF",
  },
  de: {
    nav: { resume: "Andres Diaz Lebenslauf", resumeShort: "AD Lebenslauf", about: "Über mich", skills: "Fähigkeiten", tools: "Werkzeuge", philosophy: "Philosophie", education: "Bildung", portfolio: "Portfolio", contact: "Kontakt" },
    hero: { subtitle: "Multimedia-Experte", name: "Andres Diaz", roles: "Grafikdesigner / Filmemacher / Musikproduzent / Full-Stack-Entwickler / Social-Media-Manager & Kreativer Technologe", description: "Von filmischer Erzählung bis zu polierten Webanwendungen schaffe ich End-to-End-Digitalerlebnisse, die Publikum fesseln und echte Ergebnisse liefern. Ich helfe Unternehmen, Künstlern und Marken, Verkäufe zu steigern, Sichtbarkeit zu gewinnen und sich mit professionellen, kreativen Visuals abzuheben. Mit über einem Jahrzehnt in Film, Fotografie, Grafikdesign, Musik und Code bringe ich eine einzigartige interdisziplinäre Vision in jedes Projekt.", viewWork: "Arbeit ansehen", contact: "Kontakt", resume: "Lebenslauf", scroll: "Scrollen" },
    about: { title: "Über mich", p1: "Mit über einem Jahrzehnt Erfahrung in der Multimedia-Produktion habe ich eine Karriere an der Schnittstelle von Kreativität und Technologie aufgebaut. Von der Leitung von Foto- und Video-Shootings bis zur Entwicklung von Full-Stack-Anwendungen umfasst meine Arbeit die gesamte kreative Pipeline.", p2: "Ich habe AShutter Media gegründet, um visuelle Inhalte mit großer Wirkung für Marken, Künstler und Unternehmen zu liefern. Mein Ansatz verbindet technische Präzision mit künstlerischer Vision und stellt sicher, dass jedes Projekt die Erwartungen nicht nur erfüllt, sondern übertrifft.", p3: "Ob Kinowerbespot, dynamische Social-Media-Kampagne oder maßgeschneiderte Webanwendung – ich bringe das gleiche Maß an Hingabe und Handwerkskunst in jedes Projekt. Ich glaube an die Kraft der visuellen Erzählung, zu verbinden, zu inspirieren und Ergebnisse zu liefern." },
    skills: { title: "Fähigkeiten & Disziplinen", videoEditing: "Videoschnitt", videoEditingDesc: "Professioneller Schnitt für Werbung, Filme, Social Media und Unternehmensinhalte.", photography: "Fotografie", photographyDesc: "Studio- und Location-Fotografie inkl. Porträts, Produkte, Events und Architektur.", graphicDesign: "Grafikdesign", graphicDesignDesc: "Markenidentität, Marketingmaterialien, Social-Media-Grafiken und Publikationsdesign.", musicProduction: "Musikproduktion", musicProductionDesc: "Originalkompositionen, Sounddesign, Mixing und Mastering für verschiedene Medien.", webDevelopment: "Webentwicklung", webDevelopmentDesc: "Full-Stack-Entwicklung mit modernen Frameworks, responsivem Design und optimaler Performance.", appDevelopment: "App-Entwicklung", appDevelopmentDesc: "Plattformübergreifende mobile Anwendungen mit intuitiven Oberflächen.", socialMedia: "Social Media", socialMediaDesc: "Content-Strategie, Community-Management und Wachstumsoptimierung.", motionGraphics: "Motion Graphics", motionGraphicsDesc: "Animierte Grafiken, visuelle Effekte und dynamische Inhalte für digitale und Broadcast-Medien." },
    tools: { title: "Software & Werkzeuge", creativeSoftware: "Kreativsoftware", workflowAutomation: "Workflow & Automatisierung", osPlatforms: "Betriebssysteme & Plattformen", hardware: "Hardware & Ausrüstung", musicInstruments: "Musikinstrumente" },
    philosophy: { title: "Arbeitsethik & Philosophie", precisionTitle: "Präzision & Qualität", precisionDesc: "Jeder Frame, jedes Pixel, jede Codezeile zählt.", collaborationTitle: "Zusammenarbeit", collaborationDesc: "Großartige Arbeit entsteht aus großartigen Partnerschaften.", innovationTitle: "Innovation", innovationDesc: "An der Spitze zu bleiben bedeutet, sich ständig weiterzuentwickeln.", integrityTitle: "Integrität", integrityDesc: "Ehrlichkeit und Transparenz bilden die Grundlage jeder professionellen Beziehung.", languages: "Sprachen", workPreferences: "Arbeitspräferenzen", remote: "Remote", onSite: "Vor Ort", hybrid: "Hybrid", freelance: "Freelance", fullTime: "Vollzeit", contract: "Vertrag", professionalSkills: "Berufliche Fähigkeiten", punctual: "Pünktlich & Zuverlässig", teamPlayer: "Teamplayer", quickLearner: "Schnell lernend", workEthic: "Starke Arbeitsethik", problemSolver: "Problemlöser", detailOriented: "Detailorientiert", adaptable: "Anpassungsfähig", selfMotivated: "Selbstmotiviert", creativeThinker: "Kreativer Denker", leadership: "Führung", timeManagement: "Zeitmanagement", clientRelations: "Kundenbeziehungen", moreAboutMe: "Mehr über mich", bornDate: "Geb. 13.09.1998", bornVenezuela: "Geboren in Venezuela", usCitizen: "US-Staatsbürger", loveTravel: "Reiselust", contentCreator: "Content Creator", musicProducer: "Musikproduzent", youtubeChannels: "Mehrere YouTube-Kanäle", italianFood: "Italien-Fan", languageLearner: "Sprachenlerner", loveDriving: "Fahre gern", networking: "Networking & Verbindungen", lifelongLearner: "Lebenslanger Lernender" },
    education: { title: "Bildung", highSchool: "Abitur", highSchoolInst: "Sekundarstufe", highSchoolLoc: "Allgemeinbildung", highSchoolYear: "Abgeschlossen", highSchoolDesc: "Sekundarstufe mit Fokus auf Grundlagen; frühes Interesse an Technik, Kunst und Medien.", internationalStudies: "Internationale Studien Kreativmedien", internationalInst: "Internationales Grundstudium", internationalLoc: "Multimedia, Audiovisuelle Kommunikation & Visuelle Medien", internationalYear: "2014 - 2017", internationalDesc: "Strukturiertes Grundstudium im Ausland mit Fokus auf Multimedia, Video, Fotografie und digitale Medien.", continuingEd: "Weiterbildung", continuingInst: "Fortlaufende Fortbildung & Zertifikate", continuingLoc: "Online & international anerkannte Plattformen", continuingYear: "2017 - heute", areasOfTraining: "Bereiche der Weiterbildung", creativeTools: "Kreative Tools", creativeToolsDesc: "Adobe Creative Suite, DaVinci Resolve, Final Cut Pro, KI-Tools.", photographyTraining: "Fotografie & Kinematografie", photographyTrainingDesc: "Beleuchtung, Farbkorrektur, Kamerasysteme.", audioProduction: "Audio-Produktion", audioProductionDesc: "Musikproduktion, Sounddesign, Mixing, Mastering.", marketingBusiness: "Marketing & Business", marketingBusinessDesc: "Digitale Strategien, Markenentwicklung, Kundenbeziehungen.", webAppDev: "Web- & App-Entwicklung", webAppDevDesc: "React, Next.js, Full-Stack, Mobile, Cloud.", leadershipSoftSkills: "Führung & Soft Skills", leadershipSoftSkillsDesc: "Teamarbeit, Projektführung, Kommunikation und kontinuierliches Lernen." },
    contact: { title: "Lass uns zusammenarbeiten", description: "Suche eine langfristige Rolle, in der ich mich voll einbringen kann. Ich bringe Engagement, Zuverlässigkeit und multidisziplinäre kreative und technische Fähigkeiten mit—bereit, mit Ihrem Team zu wachsen und konstant Ergebnisse zu liefern.", glowDedication: "Engagement", glowReliability: "Zuverlässigkeit", glowGrow: "bereit, mit Ihrem Team zu wachsen", emailMe: "E-Mail schreiben", callText: "Anrufen / SMS", visitPortfolio: "Portfolio besuchen", findOnline: "Online finden" },
    footer: { rights: "Alle Rechte vorbehalten.", checkPortfolio: "Portfolio ansehen" },
    scrollToTop: "Nach oben",
    language: "Sprache",
    backToSite: "Zurück zur Seite",
    downloadPdf: "PDF herunterladen",
  },
  pt: {
    nav: { resume: "Currículo Andres Diaz", resumeShort: "CV AD", about: "Sobre", skills: "Habilidades", tools: "Ferramentas", philosophy: "Filosofia", education: "Educação", portfolio: "Portfólio", contact: "Contato" },
    hero: { subtitle: "Profissional Multimídia", name: "Andres Diaz", roles: "Designer Gráfico / Cineasta / Produtor Musical / Desenvolvedor Full-Stack / Gerente de Mídias Sociais e Tecnólogo Criativo", description: "Da narrativa cinematográfica a aplicações web refinadas, crio experiências digitais completas que cativam audiências e geram resultados reais. Ajudo empresas, artistas e marcas a aumentar vendas, ganhar exposição e se destacar com visuais profissionais e criativos. Com mais de uma década em cinema, fotografia, design gráfico, música e código, trago uma visão interdisciplinar única para cada projeto.", viewWork: "Ver Trabalhos", contact: "Contato", resume: "Currículo", scroll: "Rolar" },
    about: { title: "Sobre Mim", p1: "Com mais de uma década de experiência em produção multimídia, construí uma carreira na interseção de criatividade e tecnologia. Da direção de sessões de foto e vídeo ao desenvolvimento de aplicações full-stack, meu trabalho abrange todo o pipeline criativo.", p2: "Fundei a AShutter Media para entregar conteúdo visual de alto impacto para marcas, artistas e empresas. Minha abordagem combina precisão técnica com visão artística, garantindo que cada projeto não apenas atenda mas supere as expectativas.", p3: "Seja um comercial cinematográfico, campanha dinâmica em redes sociais ou aplicação web personalizada, trago o mesmo nível de dedicação e artesanato a cada projeto. Acredito no poder da narrativa visual para conectar, inspirar e gerar resultados." },
    skills: { title: "Habilidades e Disciplinas", videoEditing: "Edição de Vídeo", videoEditingDesc: "Edição profissional para comerciais, filmes, redes sociais e conteúdo corporativo.", photography: "Fotografia", photographyDesc: "Fotografia de estúdio e locação, incluindo retratos, produtos, eventos e arquitetura.", graphicDesign: "Design Gráfico", graphicDesignDesc: "Identidade de marca, materiais de marketing, gráficos para redes sociais e design editorial.", musicProduction: "Produção Musical", musicProductionDesc: "Composições originais, design de som, mixagem e masterização.", webDevelopment: "Desenvolvimento Web", webDevelopmentDesc: "Desenvolvimento full-stack com frameworks modernos, design responsivo e performance otimizada.", appDevelopment: "Desenvolvimento de Apps", appDevelopmentDesc: "Aplicativos móveis multiplataforma com interfaces intuitivas.", socialMedia: "Mídias Sociais", socialMediaDesc: "Estratégia de conteúdo, gestão de comunidade e otimização de crescimento.", motionGraphics: "Motion Graphics", motionGraphicsDesc: "Gráficos animados, efeitos visuais e conteúdo dinâmico para mídia digital e broadcast." },
    tools: { title: "Software e Ferramentas", creativeSoftware: "Software Criativo", workflowAutomation: "Workflow e Automação", osPlatforms: "Sistemas e Plataformas", hardware: "Hardware e Equipamento", musicInstruments: "Instrumentos Musicais" },
    philosophy: { title: "Ética e Filosofia de Trabalho", precisionTitle: "Precisão e Qualidade", precisionDesc: "Cada frame, cada pixel, cada linha de código importa.", collaborationTitle: "Colaboração", collaborationDesc: "Grande trabalho surge de grandes parcerias.", innovationTitle: "Inovação", innovationDesc: "Ficar à frente significa evoluir constantemente.", integrityTitle: "Integridade", integrityDesc: "Honestidade e transparência formam a base de cada relação profissional.", languages: "Idiomas", workPreferences: "Preferências de Trabalho", remote: "Remoto", onSite: "Presencial", hybrid: "Híbrido", freelance: "Freelance", fullTime: "Tempo Integral", contract: "Contrato", professionalSkills: "Habilidades Profissionais", punctual: "Pontual e Confiável", teamPlayer: "Trabalho em Equipe", quickLearner: "Aprendiz Rápido", workEthic: "Forte Ética de Trabalho", problemSolver: "Resolvedor de Problemas", detailOriented: "Orientado a Detalhes", adaptable: "Adaptável", selfMotivated: "Automotivado", creativeThinker: "Pensador Criativo", leadership: "Liderança", timeManagement: "Gestão do Tempo", clientRelations: "Relações com Clientes", moreAboutMe: "Mais Sobre Mim", bornDate: "Nascido 13/09/1998", bornVenezuela: "Nascido na Venezuela", usCitizen: "Cidadão dos EUA", loveTravel: "Amo Viajar", contentCreator: "Criador de Conteúdo", musicProducer: "Produtor Musical", youtubeChannels: "Múltiplos Canais no YouTube", italianFood: "Entusiasta da Cozinha Italiana", languageLearner: "Aprendiz de Idiomas", loveDriving: "Amo Dirigir", networking: "Networking e Conexões", lifelongLearner: "Aprendiz por Toda a Vida" },
    education: { title: "Educação", highSchool: "Diploma do Ensino Médio", highSchoolInst: "Educação Secundária", highSchoolLoc: "Estudos Gerais e Fundamentos", highSchoolYear: "Concluído", highSchoolDesc: "Concluí o ensino médio com foco em fundamentos acadêmicos.", internationalStudies: "Estudos Internacionais em Mídia Criativa", internationalInst: "Educação Internacional de Graduação", internationalLoc: "Artes Multimídia, Comunicação Audiovisual e Mídia Visual", internationalYear: "2014 - 2017", internationalDesc: "Estudos estruturados de nível superior no exterior focados em multimídia, vídeo, fotografia e mídia digital.", continuingEd: "Desenvolvimento Profissional Contínuo", continuingInst: "Treinamento Avançado, Certificações e Cursos de Graduação", continuingLoc: "Plataformas Online e Reconhecidas Internacionalmente", continuingYear: "2017 - Presente", areasOfTraining: "Áreas de Treinamento Contínuo", creativeTools: "Ferramentas Criativas Avançadas", creativeToolsDesc: "Adobe Creative Suite, DaVinci Resolve, Final Cut Pro e ferramentas com IA.", photographyTraining: "Fotografia e Cinematografia", photographyTrainingDesc: "Técnicas de iluminação, correção de cor, câmeras.", audioProduction: "Produção de Áudio", audioProductionDesc: "Produção musical, design de som, mixagem, masterização.", marketingBusiness: "Marketing e Negócios", marketingBusinessDesc: "Estratégias digitais, desenvolvimento de marca, relações com clientes.", webAppDev: "Desenvolvimento Web e Apps", webAppDevDesc: "React, Next.js, full-stack, mobile, cloud.", leadershipSoftSkills: "Liderança e Soft Skills", leadershipSoftSkillsDesc: "Colaboração em equipe, liderança de projetos, comunicação e aprendizagem contínua." },
    contact: { title: "Vamos Trabalhar Juntos", description: "Buscando um papel de longo prazo onde possa me comprometer totalmente. Trago dedicação, confiabilidade e habilidades criativas e técnicas multidisciplinares—pronto para crescer com sua equipe e entregar resultados consistentes como membro comprometido.", glowDedication: "dedicação", glowReliability: "confiabilidade", glowGrow: "pronto para crescer com sua equipe", emailMe: "Enviar Email", callText: "Ligar / Mensagem", visitPortfolio: "Visitar Meu Portfólio", findOnline: "Encontre-me online" },
    footer: { rights: "Todos os direitos reservados.", checkPortfolio: "Ver meu portfólio" },
    scrollToTop: "Voltar ao topo",
    language: "Idioma",
    backToSite: "Voltar ao site",
    downloadPdf: "Baixar PDF",
  },
  it: {
    nav: { resume: "CV Andres Diaz", resumeShort: "CV AD", about: "Chi sono", skills: "Competenze", tools: "Strumenti", philosophy: "Filosofia", education: "Formazione", portfolio: "Portfolio", contact: "Contatto" },
    hero: { subtitle: "Professionista Multimediale", name: "Andres Diaz", roles: "Graphic Designer / Filmmaker / Music Producer / Sviluppatore Full-Stack / Social Media Manager e Creative Technologist", description: "Dalla narrazione cinematografica alle applicazioni web raffinate, creo esperienze digitali end-to-end che catturano il pubblico e generano risultati concreti. Aiuto aziende, artisti e brand ad aumentare le vendite, ottenere visibilità e distinguersi con visual professionali e creativi. Con oltre un decennio tra cinema, fotografia, graphic design, musica e codice, porto una visione interdisciplinare unica in ogni progetto.", viewWork: "Vedi Lavori", contact: "Contatto", resume: "CV", scroll: "Scorri" },
    about: { title: "Chi Sono", p1: "Con oltre un decennio di esperienza nella produzione multimediale, ho costruito una carriera all'incrocio tra creatività e tecnologia. Dalla direzione di shooting foto e video allo sviluppo di applicazioni full-stack, il mio lavoro copre l'intera pipeline creativa.", p2: "Ho fondato AShutter Media per fornire contenuti visivi ad alto impatto per brand, artisti e aziende. Il mio approccio combina precisione tecnica e visione artistica, assicurando che ogni progetto non solo soddisfi ma superi le aspettative.", p3: "Che sia uno spot cinematografico, una campagna social dinamica o un'app web su misura, porto lo stesso livello di dedizione e artigianalità in ogni progetto. Credo nel potere della narrazione visiva per connettere, ispirare e generare risultati." },
    skills: { title: "Competenze e Discipline", videoEditing: "Montaggio Video", videoEditingDesc: "Montaggio professionale per spot, film, social e contenuti corporate.", photography: "Fotografia", photographyDesc: "Fotografia in studio e on location: ritratti, prodotti, eventi, architettura.", graphicDesign: "Graphic Design", graphicDesignDesc: "Identità di marca, materiali di marketing, grafiche social, design editoriale.", musicProduction: "Produzione Musicale", musicProductionDesc: "Composizioni originali, sound design, mix e mastering.", webDevelopment: "Sviluppo Web", webDevelopmentDesc: "Sviluppo full-stack con framework moderni, design responsive e performance.", appDevelopment: "Sviluppo App", appDevelopmentDesc: "App mobili multipiattaforma con interfacce intuitive.", socialMedia: "Social Media", socialMediaDesc: "Strategia dei contenuti, community management, ottimizzazione della crescita.", motionGraphics: "Motion Graphics", motionGraphicsDesc: "Grafiche animate, effetti visivi e contenuti dinamici per digitale e broadcast." },
    tools: { title: "Software e Strumenti", creativeSoftware: "Software Creativo", workflowAutomation: "Workflow e Automazione", osPlatforms: "Sistemi e Piattaforme", hardware: "Hardware e Attrezzature", musicInstruments: "Strumenti Musicali" },
    philosophy: { title: "Etica e Filosofia del Lavoro", precisionTitle: "Precisione e Qualità", precisionDesc: "Ogni frame, ogni pixel, ogni riga di codice conta.", collaborationTitle: "Collaborazione", collaborationDesc: "I grandi lavori nascono da grandi partnership.", innovationTitle: "Innovazione", innovationDesc: "Restare avanti significa evolversi costantemente.", integrityTitle: "Integrità", integrityDesc: "Onestà e trasparenza sono la base di ogni relazione professionale.", languages: "Lingue", workPreferences: "Preferenze di Lavoro", remote: "Remoto", onSite: "In Sede", hybrid: "Ibrido", freelance: "Freelance", fullTime: "Tempo Pieno", contract: "Contratto", professionalSkills: "Competenze Professionali", punctual: "Puntuale e Affidabile", teamPlayer: "Lavoro di Squadra", quickLearner: "Apprendimento Rapido", workEthic: "Forte Etica del Lavoro", problemSolver: "Problem Solver", detailOriented: "Orientato ai Dettagli", adaptable: "Adattabile", selfMotivated: "Auto-motivato", creativeThinker: "Pensatore Creativo", leadership: "Leadership", timeManagement: "Gestione del Tempo", clientRelations: "Relazioni con i Clienti", moreAboutMe: "Altro su di Me", bornDate: "Nato 13/09/1998", bornVenezuela: "Nato in Venezuela", usCitizen: "Cittadino USA", loveTravel: "Amo Viaggiare", contentCreator: "Content Creator", musicProducer: "Music Producer", youtubeChannels: "Multipli Canali YouTube", italianFood: "Appassionato di Cucina Italiana", languageLearner: "Studente di Lingue", loveDriving: "Amo Guidare", networking: "Networking e Connessioni", lifelongLearner: "Apprendimento Permanente" },
    education: { title: "Formazione", highSchool: "Diploma di Scuola Superiore", highSchoolInst: "Istruzione Secondaria", highSchoolLoc: "Studi Generali e Fondamenti", highSchoolYear: "Completato", highSchoolDesc: "Istruzione secondaria con focus su fondamenti accademici.", internationalStudies: "Studi Internazionali in Media Creativi", internationalInst: "Istruzione Universitaria Internazionale", internationalLoc: "Arti Multimediali, Comunicazione Audiovisiva e Media Visivi", internationalYear: "2014 - 2017", internationalDesc: "Studi strutturati di livello universitario all'estero su multimedia, video, fotografia e media digitali.", continuingEd: "Sviluppo Professionale Continuo", continuingInst: "Formazione Avanzata, Certificazioni e Corsi Universitari", continuingLoc: "Piattaforme Online e Riconosciute a Livello Internazionale", continuingYear: "2017 - Presente", areasOfTraining: "Aree di Formazione Continua", creativeTools: "Strumenti Creativi Avanzati", creativeToolsDesc: "Adobe Creative Suite, DaVinci Resolve, Final Cut Pro e strumenti con IA.", photographyTraining: "Fotografia e Cinematografia", photographyTrainingDesc: "Tecniche di illuminazione, color grading, sistemi camera.", audioProduction: "Produzione Audio", audioProductionDesc: "Produzione musicale, sound design, mix, mastering.", marketingBusiness: "Marketing e Business", marketingBusinessDesc: "Strategie digitali, sviluppo del brand, relazioni con i clienti.", webAppDev: "Sviluppo Web e App", webAppDevDesc: "React, Next.js, full-stack, mobile, cloud.", leadershipSoftSkills: "Leadership e soft skill", leadershipSoftSkillsDesc: "Collaborazione in team, leadership di progetto, comunicazione e apprendimento continuo." },
    contact: { title: "Lavoriamo Insieme", description: "Cerco un ruolo a lungo termine in cui impegnarmi a fondo. Porto dedizione, affidabilità e competenze creative e tecniche multidisciplinari—pronto a crescere con il tuo team e a dare risultati costanti come membro impegnato.", glowDedication: "dedizione", glowReliability: "affidabilità", glowGrow: "pronto a crescere con il tuo team", emailMe: "Scrivimi", callText: "Chiama / SMS", visitPortfolio: "Visita il Mio Portfolio", findOnline: "Trovami online" },
    footer: { rights: "Tutti i diritti riservati.", checkPortfolio: "Vedi il mio portfolio" },
    scrollToTop: "Torna su",
    language: "Lingua",
    backToSite: "Torna al sito",
    downloadPdf: "Scarica PDF",
  },
};
